services:
  toolbox:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"  # Frontend port
      - "8020:8020"  # Backend API port
    volumes:
      # For development: mount source directories to enable hot-reload
      - ./backend:/app/backend
      - ./frontend/src:/app/frontend/src
      - /var/run/docker.sock:/var/run/docker.sock # Mount Docker socket
      # Mount repository cache for persistence
      - ./mcp_cache:/app/mcp_cache
    environment:
      - BACKEND_URL=http://localhost:8020
      # Choose one of the following Qdrant configurations based on your setup:
      
      # Option 1: Use host.docker.internal to connect to Qdrant on the host machine
      - QDRANT_HOST=host.docker.internal
      - QDRANT_PORT=7333

      # Option 2: Use the host's IP address directly (if host.docker.internal doesn't work)
      #- QDRANT_HOST=192.168.194.33
      #- QDRANT_PORT=7333
      
      # Option 3: Use a service name if Qdrant is running in another Docker container
      # - QDRANT_HOST=qdrant
      # - QDRANT_PORT=6333
      
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Required for Docker to resolve host.docker.internal
    restart: unless-stopped
    
# Uncomment this if you want to run Qdrant in Docker too
#  qdrant:
#   image: qdrant/qdrant
#   ports:
#     - "6333:6333"
#     - "6334:6334"
#   volumes:
#     - qdrant_data:/qdrant/storage
#   restart: unless-stopped

#volumes:
 #  qdrant_data: 
